Implement block device abstraction (#1)
psarna/seastar pull request #11
Opened 2019-11-13 09:37 UTC by varqox

2019-11-17 13:52 UTC, psarna requested changes
General request - before merging, please squash all fixup commits (like `Fixed block_device unit test`) with `git rebase -i` and repush with `git push -f`. Seastar keeps a clear git history, which means that a single series should not contain fixes to itself - instead, series are always rebased and squashed in order to ensure they are clear.

2019-11-17 13:52 UTC, psarna commented on tests/unit/block_device_test.cc
> +constexpr off_t min_device_size = 16 << 20; // 16 MiB
we have KB, MB and GB defined in `seastar/core/units.hh`, feel free to use them instead of manual shifts:
`min_device_size = 16*MB`

2019-11-17 13:52 UTC, psarna commented on tests/unit/block_device_test.cc
> +        constexpr size_t buff_size = 16 << 20;
ditto, 16*MB looks nicer

2019-11-17 13:52 UTC, psarna commented on tests/unit/block_device_test.cc
> +        size_t blocks = buff_size / alignment;
for a variable that represents a size, use `blocks_num` or `blocks_count` - `blocks` suggests that it's a data structure with blocks inside

2019-11-17 13:52 UTC, psarna commented on include/seastar/fs/block_device.hh
> -
code style request - either drop this change or move it to the previous commit. This commit should only contain changes to the unit test.

2019-11-17 19:24 UTC, rokinsky requested changes

2019-11-17 19:24 UTC, rokinsky commented on include/seastar/fs/block_device.hh
> +    virtual ~file_block_device_impl() override = default;
```suggestion
   ~file_block_device_impl() override = default;
```
`virtual` is redundant

2019-11-17 19:24 UTC, rokinsky commented on include/seastar/fs/block_device.hh
> +    file_block_device_impl(file f) : _file(std::move(f)) {}
```suggestion
    explicit file_block_device_impl(file f) : _file(std::move(f)) {}
```
Single argument constructors must be marked `explicit`

2019-11-17 19:24 UTC, rokinsky commented on include/seastar/fs/block_device.hh
> +    virtual ~block_device_impl() {}
```suggestion
    virtual ~block_device_impl() = default
```

2019-11-17 19:24 UTC, rokinsky commented on include/seastar/fs/block_device.hh
> +future<block_device> open_block_device(sstring name) {
```suggestion
inline future<block_device> open_block_device(sstring name) {
```
Without `inline` keyword here, I have a multiple definition linker error.

2019-11-19 09:28 UTC, psarna commented
Let's make `block_device` aware of `io_priority_class`, as `seastar::file` is. We'll use the default class for now anyway, but priority classes are crucial for performance, so the API should contain them from the start.

2019-11-19 10:16 UTC, varqox commented
How namespaces should be used?
Should block_device and other functionality implemented in zpp_fs be in `seastar` or `seastar::fs` namespace?
Should temporary_file be in `seastar::fs` or `seastar::util` or `seastar::fs::util`?

Regarding pull requests, I understand that commits should be neatly divided so that each adds some part of the whole without touching others (e.g. no fixes) and it should be done before merging. So before the pull is ready for merging, we are supposed to clean the commits or not to clean the commits to make the review easier? If the second option is better, should one as for another round of review after cleaning the commits or just make a merge or something else?

2019-11-19 10:31 UTC, rokinsky reviewed
Looks good.

2019-11-19 10:40 UTC, psarna commented
@varqox Let's keep everything in `seastar::fs` so our changes are well separated. Also, no need for `seastar::fs::util`, it's fine for everything to reside in `seastar::fs`.

As for squashing commits, it's actually easier for me to review a clean series instead of a branch full of fixups. It's totally fine to push fixups when developing the change, but it's best if they're cleaned before the final review (the best option would be just to use gerrit, but for now we're restricted to github and its hyper-unintuitive way it presents commits in pull requests).

By the way, for now the list of maintainers which are capable of merging a request to our branch are: me, @haaawk and @kbr-. Once the change is accepted it will be merged by one of us - that way the git tree is more likely to be clean enough to become a merging candidate for seastar/master later.

2019-11-19 19:55 UTC, haaawk commented on include/seastar/fs/temporary_file.hh
> +    temporary_file(const temporary_file &) = delete;
This uses wrong convention: '&' should be next to temporary_file with no space.

2019-11-19 19:56 UTC, haaawk commented on include/seastar/fs/temporary_file.hh
> +    temporary_file &operator=(const temporary_file &) = delete;
s/temporary_file &/temporary_file&/

2019-11-19 19:56 UTC, haaawk commented on include/seastar/fs/temporary_file.hh
> +    temporary_file(temporary_file &&) noexcept = delete;
remove space between temporary_file and &&

2019-11-19 19:57 UTC, haaawk commented on include/seastar/fs/temporary_file.hh
> +    temporary_file &operator=(temporary_file &&) noexcept = delete;
remove space between temporary_file and &&
also remove space between temporary_file and &

2019-11-20 09:22 UTC, psarna approved these changes

2019-11-20 09:23 UTC, merged