Add bootstrap record
psarna/seastar pull request #37
Opened 2019-12-12 08:39 UTC by tropuq

See #29

2019-12-12 10:41 UTC, psarna commented
Thanks, nice. General remarks after a cursory review:

1. Let's settle on little endian - it's more common and it's used in our target architecture, so let's not spend CPU time on endian conversions (well, the magic number is traditionally expected to be big-endian, but SFALLYCS it quite a unique sequence of bytes too :smile:)
2. Please squash all the fixups and refactors, so that we have clear git history

2019-12-16 18:29 UTC, rokinsky requested changes

2019-12-16 18:29 UTC, rokinsky commented on src/fs/bootstrap_record.cc
> +        uint32_t crc_calc = crc32(boot_record_buff.get(), crc_offset);
```suggestion
        const uint32_t crc_calc = crc32(boot_record_buff.get(), crc_offset);
```

2019-12-16 18:29 UTC, rokinsky commented on src/fs/bootstrap_record.cc
> +        uint32_t crc_read = boot_record_disk.crc;
```suggestion
        const uint32_t crc_read = boot_record_disk.crc;
```

2019-12-16 18:29 UTC, rokinsky commented on src/fs/bootstrap_record.cc
> +        uint64_t magic_read = boot_record_disk.magic;
```suggestion
        const uint64_t magic_read = boot_record_disk.magic;
```

2019-12-16 18:29 UTC, rokinsky commented on src/fs/bootstrap_record.cc
> +    uint32_t crc = crc32(boot_record_buff.get(), crc_offset);
```suggestion
    const uint32_t crc = crc32(boot_record_buff.get(), crc_offset);
```

2019-12-16 18:29 UTC, rokinsky commented on tests/unit/bootstrap_record_test.cc
> +    uint32_t* crc_value = (uint32_t*)(buff.data() + crc_pos);
Don't use C-style cast.

2019-12-16 18:29 UTC, rokinsky commented on tests/unit/bootstrap_record_test.cc
> +    T* value_ptr = (T*)(dev_impl.get()->buf.data() + offset);
Don't use C-style cast.

2019-12-16 20:45 UTC, wmitros commented on tests/unit/bootstrap_record_test.cc
> +                BOOST_REQUIRE_EQUAL(write_record.cluster_size, read_record.cluster_size);
Missing writes of the changed write_record to disk, you probably want to compare changed values instead of cluster_size too.

2019-12-18 23:07 UTC, varqox commented on CMakeLists.txt
> +  src/fs/bootstrap_record.cc
Add bootstrap_record.hh

2019-12-26 23:54 UTC, closed without merging