Add src/fs/cluster.hh
psarna/seastar pull request #44
Opened 2019-12-18 23:14 UTC by varqox

2019-12-18 23:45 UTC, tropuq requested changes

2019-12-18 23:45 UTC, tropuq commented on src/fs/cluster.hh
> +inline offset_t offset_to_cluster_id(offset_t offset, uint32_t cluster_size) noexcept {
```suggestion
inline cluster_id_t offset_to_cluster_id(offset_t offset, uint32_t cluster_size) noexcept {
```

2019-12-18 23:53 UTC, rokinsky commented on src/fs/cluster.hh
> +	return (x > 0 and (x & (x - 1)) == 0);
```suggestion
	return x > 0 and (x & (x - 1)) == 0;
```

2019-12-18 23:53 UTC, rokinsky commented on src/fs/cluster.hh
> +	return (offset >> __builtin_ctzll(cluster_size)); // should be 2 CPU cycles after inlining on modern x86_64
```suggestion
	return offset >> __builtin_ctzll(cluster_size); // should be 2 CPU cycles after inlining on modern x86_64
```

2019-12-19 09:13 UTC, varqox commented on src/fs/cluster_allocator.hh
> +    explicit cluster_allocator(std::queue<cluster_id_t>);
Add some way to provide allocated clusters

2019-12-19 14:16 UTC, varqox commented on src/fs/cluster_allocator.hh
> +    explicit cluster_allocator(std::unordered_set<cluster_id_t>, std::queue<cluster_id_t>);
Add names of parameters @wmitros

2019-12-19 14:16 UTC, varqox commented on src/fs/cluster_allocator.hh
> +#include "fs/cluster.hh"
Should we add newline between "..." and <...> includes?

2019-12-21 00:47 UTC, tropuq requested changes

2019-12-21 00:47 UTC, tropuq commented on src/fs/cluster.hh
> +inline cluster_id_t offset_to_cluster_id(offset_t offset, uint32_t cluster_size) noexcept {
```suggestion
inline cluster_id_t offset_to_cluster_id(offset_t offset, unit_size_t cluster_size) noexcept {
```

2019-12-21 00:47 UTC, tropuq commented on src/fs/cluster.hh
> +inline offset_t cluster_id_to_offset(cluster_id_t cluster_id, uint32_t cluster_size) noexcept {
```suggestion
inline offset_t cluster_id_to_offset(cluster_id_t cluster_id, unit_size_t cluster_size) noexcept {
```

2019-12-26 23:54 UTC, closed without merging

2019-12-26 23:59 UTC, varqox commented
Renamed branch to fs-unit-headers -- see #47