fs: rename block to cluster
psarna/seastar pull request #48
Opened 2019-12-28 20:50 UTC by wmitros

2019-12-28 22:27 UTC, varqox commented
Note for merger: This PR, should be **merged after** #47.

2020-01-07 15:56 UTC, psarna reviewed
Please add a short changelog and motivation in the commit message. Renaming from block to cluster is fine, but ` fs: Refactored cluster_allocator ` is not enough - let's write a line or two that optional is chosen instead of 0 and there's a deque now.

2020-01-07 23:10 UTC, varqox requested changes
Please correct these small code-style related issues

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    fs::cluster_allocator small_ca(empty_uset, deq);
```suggestion
    fs::cluster_allocator small_ca({}, deq);
```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    BOOST_REQUIRE(small_ca.alloc() == std::nullopt);
```suggestion
    BOOST_REQUIRE(small_ca.alloc() == std::nullopt);

```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    BOOST_REQUIRE_EQUAL(small_ca.alloc().value(), deq[3]);
```suggestion
    BOOST_REQUIRE_EQUAL(small_ca.alloc().value(), deq[3]);

```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    fs::cluster_allocator ordinary_ca(empty_uset, dq);
```suggestion
    fs::cluster_allocator ordinary_ca({}, dq);
```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    std::unordered_set<fs::cluster_id_t> empty_uset;
```suggestion
```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    std::unordered_set<fs::cluster_id_t> empty_uset;
```suggestion
```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    std::deque<fs::cluster_id_t> dq;
```suggestion
    std::deque<fs::cluster_id_t> deq;
```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    std::unordered_set<fs::cluster_id_t> empty_uset;
```suggestion
```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    fs::cluster_allocator empty_ca{empty_uset, {}};
```suggestion
    fs::cluster_allocator empty_ca{{}, {}};
```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    }
```suggestion
    }
    BOOST_REQUIRE(ordinary_ca.alloc() == std::nullopt);
```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +}
```suggestion
}

```

2020-01-07 23:10 UTC, varqox commented on tests/unit/cluster_allocator_test.cc
> +    std::deque<fs::cluster_id_t> dq;
```suggestion
    std::deque<fs::cluster_id_t> deq;
```

2020-01-09 12:07 UTC, psarna commented
merging #47 created conflicts, please rebase

2020-01-10 14:07 UTC, merged